export const fonts = {
  SFProDisplayBlack: 'SF-Pro-Display-Black',
  SFProDisplayBlackItalic: 'SF-Pro-Display-BlackItalic',
  SFProDisplayBold: 'SF-Pro-Display-Bold',
  SFProDisplayBoldItalic: 'SF-Pro-Display-BoldItalic',
  SFProDisplayHeavy: 'SF-Pro-Display-Heavy',
  SFProDisplayHeavyItalic: 'SF-Pro-Display-HeavyItalic',
  SFProDisplayLight: 'SF-Pro-Display-Light',
  SFProDisplayLightItalic: 'SF-Pro-Display-LightItalic',
  SFProDisplayMedium: 'SF-Pro-Display-Medium',
  SFProDisplayMediumItalic: 'SF-Pro-Display-MediumItalic',
  SFProDisplayRegular: 'SF-Pro-Display-Regular',
  SFProDisplayRegularItalic: 'SF-Pro-Display-RegularItalic',
  SFProDisplaySemiBold: 'SF-Pro-Display-Semibold',
  SFProDisplaySemiBoldItalic: 'SF-Pro-Display-SemiboldItalic',
  SFProDisplayThin: 'SF-Pro-Display-Thin',
  SFProDisplayThinItalic: 'SF-Pro-Display-ThinItalic',
  SFProDisplayUltralight: 'SF-Pro-Display-Ultralight',
  SFProDisplayUltraLightItalic: 'SF-Pro-Display-UltralightItalic',
};
